version: "3.4"

services:
  web:
    restart: unless-stopped
    build: ./
    volumes:
      - public_folder:/app/public
    environment:
      ENV: "production"
    command: gunicorn --workers=4 --threads=8 --worker-tmp-dir /dev/shm --worker-class=gthread -b 0.0.0.0:8000 app:app
    # /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    networks:
      - api

  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - public_folder:/code/static
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  public_folder:
